# Generated by Django 2.1.5 on 2023-08-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='avaliações',
            new_name='avaliacoes',
        ),
    ]
