# Generated by Django 2.1.5 on 2023-08-23 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230822_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIdentificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('numero', models.IntegerField(verbose_name='Número')),
            ],
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='doc_identificacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DocumentoIdentificacao', verbose_name='Documento de Identificação'),
        ),
    ]
