# Generated by Django 2.0.4 on 2023-08-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('horario_funcionamento', models.TextField(verbose_name='Horário de funcionamento')),
                ('idade_minima', models.IntegerField(verbose_name='Idade mínima')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
                'db_table': 'atracao',
            },
        ),
    ]
