# Generated by Django 4.1 on 2023-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracao', '0002_atracao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
